
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SHEETS_API_KEY = "your_google_sheets_api_key_here"
  VITE_SHEET_ID = "your_google_sheet_id_here"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
